#!/bin/sh
set -eu

# ----------------------------------------------------------------------------------------------------------------------

echo "► Starting Main Entrypoint..."

# --------------------------------------------------------------------------------------------------------------------

# Run Dockerfile's CMD (default: $> php-fpm )
echo "► Starting application with doppler... cmd: ${@}"
exec doppler run --command="$@"
